[features]
seeds = false
skip-lint = false
[programs.devnet]
kanban = "WBAeGBvBarw39HZPfKjQnYKH57FcVJTmvGyDDSMwZwq"
[programs.localnet]
kanban = "WBAeGBvBarw39HZPfKjQnYKH57FcVJTmvGyDDSMwZwq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
